### ISSUE TITLE
Minimum length strings

### ISSUE THREAD

**Issue by Miserlou** [rdegges/brute#2]
Length=n will still iterate through all of the 1,2,3,..,n-1 length strings as well.

If I _only_ want n length strings, I should be able to call brute(minimum=n) or something similar!

**Comment by rdegges** [comment]
Thanks for the suggestion =)

Just added a 'ramp' option (defaults to True). If you disable it, the library will no longer 'ramp up' from 1 -> length, instead it'll just process the specified length strings.

<33

**Comment by rdegges** [comment]
Also: cut a new PyPI release (0.0.2) so you can get this if you upgrade.
